{
 "title": "FlowSentinel Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://backend:5000/metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Events",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"flow-sentinel\"} |= ``"
    }
   ]
  },
  {
   "title": "Production per day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts as day, sum(val) as total FROM metrics WHERE $__timeFilter(ts) SAMPLE BY 1d FILL(0) ALIGN TO CALENDAR TIME ZONE '$__timezone'"
    }
   ]
  }
 ]
}